### ISSUE TITLE
Update design according to README

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma-nist-style#1]
@pierrefortier can we use the color palette for NIST (shown in the README)?

And could we make it look more "serious/professional" as according to the cover pages shown (in the README), and also add the "NIST" and "Department of Commerce" logo somewhere?

Thanks!

CC: @opoudjis

**Comment by pierrefortier** [comment]
Here's an update to the template that better reflects their style guide.

[NIST-style-v2.zip](https://github.com/riboseinc/metanorma-nist-style/files/2734124/NIST-style-v2.zip)

**Comment by ronaldtse** [comment]
Thank you @pierrefortier ! The general styling looks good:

* Table content is not very readable, can we adjust the table coloring with black text?
* Great choice to add the Department of Commerce colored logo!

@opoudjis could you please help implement the styling? Thanks!

**Comment by pierrefortier** [comment]
Great! Here's the styling with black text for the tables:

[NIST-style-v3.zip](https://github.com/riboseinc/metanorma-nist-style/files/2738056/NIST-style-v3.zip)

**Comment by ronaldtse** [comment]
Thanks! One more thing, we need to have a place to show authors and their affiliations. Eg. https://github.com/riboseinc/metanorma-nist/issues/13

(The figure on the right)

Could you pleas help us devise a good layout for it? Thanks!

**Comment by pierrefortier** [comment]
Sure thing! I've included authors and affiliations here:

[NIST-style-v4.zip](https://github.com/riboseinc/metanorma-nist-style/files/2741408/NIST-style-v4.zip)

**Comment by ronaldtse** [comment]
I just realized we have some additional data to provide. See the cover pages below (outer cover + inner cover). Could you please help add them in too? Thanks @pierrefortier !

(Outer)

![screen shot 2019-01-09 at 11 53 14 pm](https://user-images.githubusercontent.com/11865/50911192-4ea47380-146a-11e9-8440-66c3a3000dcb.png)

(Inner)

![screen shot 2019-01-09 at 11 53 21 pm](https://user-images.githubusercontent.com/11865/50911115-2583e300-146a-11e9-9bbf-28bfdaff8cda.png)

**Comment by pierrefortier** [comment]
Sure! The requested info has been integrated:

[NIST-style-v5.zip](https://github.com/riboseinc/metanorma-nist-style/files/2742143/NIST-style-v5.zip)

**Comment by ronaldtse** [comment]
Thank you @pierrefortier ! This has been merged to master.

ping: @opoudjis -- the HTML style is now at master.
