### ISSUE TITLE
Create styles for NIST draft states

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma-nist-style#4]
@pierrefortier could you please help implement these draft states for the NIST document style?

Specifically, they are listed in https://github.com/metanorma/metanorma-nist/issues/79#issuecomment-477119489

Thanks!

**Comment by opoudjis** [comment]
@pierrefortier, you will need the latest CSS. I attach a sample document:

[NIST.SP.800-116r1.html.zip](https://github.com/metanorma/metanorma-nist-style/files/3016592/NIST.SP.800-116r1.html.zip)

**Comment by ronaldtse** [comment]
(@opoudjis isn't it easier to replace the content in this repo with the files from your archive?)

**Comment by opoudjis** [comment]
It is, I just hadn't noticed it :)

**Comment by opoudjis** [comment]
There is one further draft state that needs to be modelled: A document which isn't currently withdrawn, but will be withdrawn in the future. See the front page of https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-37r1.pdf

**Comment by ronaldtse** [comment]
@pierrefortier to make things simpler:

A. Design for "DRAFT" publication:

design 1: front page notice
<img width="545" alt="image" src="https://user-images.githubusercontent.com/11865/55465095-fdea8400-562e-11e9-9e39-b624cac36419.png">

design 2: call for comments
<img width="581" alt="image" src="https://user-images.githubusercontent.com/11865/55465019-e01d1f00-562e-11e9-8e2c-b9e7ed10b982.png">

design 3: call for patent claims
<img width="595" alt="image" src="https://user-images.githubusercontent.com/11865/55465037-e9a68700-562e-11e9-99de-b3b4fe498053.png">

B. Retired draft cover page
![image](https://user-images.githubusercontent.com/11865/55465125-1064bd80-562f-11e9-8bf4-84ba016a123d.png)

C. Withdrawn document cover page
![image](https://user-images.githubusercontent.com/11865/55465141-18bcf880-562f-11e9-97c3-ca05d37cea1a.png)

D. To-be-withdrawn document notice
![image](https://user-images.githubusercontent.com/11865/55465155-23778d80-562f-11e9-9098-e9ba89f91e6e.png)


I think B, C, D should all look similar (despite that they look different in these images).

**Comment by pierrefortier** [comment]
Sorry for the late reply, I'll get this back to you ASAP!

**Comment by pierrefortier** [comment]
Here is a zip with all of the drafts! 
[NIST-DRAFTS.zip](https://github.com/metanorma/metanorma-nist-style/files/3049915/NIST-DRAFTS.zip)

**Comment by ronaldtse** [comment]
@pierrefortier thanks!

The covers have received new updates -- there are 3 types of them:

1. Draft cover pages https://github.com/metanorma/metanorma-nist/issues/99
2. Retired and Withdrawn drafts https://github.com/metanorma/metanorma-nist/issues/100
3. Entire publication withdrawn https://github.com/metanorma/metanorma-nist/issues/101

Can we style these 3 types separately (e.g. colors), yet have a consistent layout that provides the information shown?

Thanks!

**Comment by pierrefortier** [comment]
Hi @ronaldtse, here are the new drafts!

[NIST-drafts-v2.zip](https://github.com/metanorma/metanorma-nist-style/files/3100156/NIST-drafts-v2.zip)

**Comment by opoudjis** [comment]
@ronaldtse  Will wait on confirmation from you before actioning

**Comment by ronaldtse** [comment]
@pierrefortier sorry for the late reply!

For the inactive drafts, could you update the left banner colors/states (e.g. "FINAL - WITHDRAWAL PENDING 2019-04-25") so that they look the way it's supposed to feel?

e.g. a "Withdrawn" draft/document should have the red color and warning plastered all over.

Thanks!

**Comment by pierrefortier** [comment]
Sure! Here are the updates.

[NIST-drafts-v3.zip](https://github.com/metanorma/metanorma-nist-style/files/3124994/NIST-drafts-v3.zip)

**Comment by ronaldtse** [comment]
Thanks @pierrefortier! Let's close this.
